########## 3.1.5. Pontuação do teste de permutação  ##########

    # permutation_test_score oferece outra maneira de avaliar o desempenho dos classificadores. Ele fornece um valor p baseado em permutação, que representa a probabilidade de um desempenho observado do classificador ser obtido por acaso. A hipótese nula neste teste é que o classificador falha em aproveitar qualquer dependência estatística entre os recursos e os rótulos para fazer previsões corretas sobre os dados omitidos. permutation_test_score gera uma distribuição nula calculando n_permutations diferentes permutações dos dados. Em cada permutação, os rótulos são embaralhados aleatoriamente, removendo assim qualquer dependência entre os recursos e os rótulos. A saída do valor p é a fração de permutações para a qual a pontuação média da validação cruzada obtida pelo modelo é melhor do que a pontuação da validação cruzada obtida pelo modelo usando os dados originais. Para resultados confiáveis, as n_permutações devem ser normalmente maiores que 100 e cv entre 3-10 dobras.

    # Um valor de p baixo fornece evidências de que o conjunto de dados contém dependência real entre recursos e rótulos e o classificador foi capaz de utilizar isso para obter bons resultados. Um valor p alto pode ser devido à falta de dependência entre recursos e rótulos (não há diferença nos valores dos recursos entre as classes) ou porque o classificador não foi capaz de usar a dependência nos dados. No último caso, o uso de um classificador mais adequado, capaz de utilizar a estrutura dos dados, resultaria em um valor de p menor.

    # A validação cruzada fornece informações sobre o quão bem um classificador generaliza, especificamente a faixa de erros esperados do classificador. No entanto, um classificador treinado em um conjunto de dados de alta dimensão sem estrutura pode ainda ter um desempenho melhor do que o esperado na validação cruzada, apenas por acaso. Normalmente, isso pode acontecer com pequenos conjuntos de dados com menos de algumas centenas de amostras. permutation_test_score fornece informações sobre se o classificador encontrou uma estrutura de classe real e pode ajudar na avaliação do desempenho do classificador.

    # É importante notar que este teste mostrou produzir valores p baixos, mesmo se houver apenas uma estrutura fraca nos dados, porque nos conjuntos de dados permutados correspondentes não há absolutamente nenhuma estrutura. Portanto, esse teste só é capaz de mostrar quando o modelo supera de forma confiável a suposição aleatória.

    # Finalmente, permutation_test_score é calculado usando força bruta e se ajusta internamente (n_permutations + 1) * modelos n_cv. Portanto, é apenas tratável com pequenos conjuntos de dados, para os quais o ajuste de um modelo individual é muito rápido. 